# -*- coding: utf-8 -*-
"""INTERFACE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Umg_FzBJ6UWlnzGfREMuFxXOGR_sLsj1
"""

import os
import sys
import re
import importlib.util
from google.colab import drive
import json # Import json module

# 1. Mount Drive
drive.mount('/content/drive')
model_folder_path = '/content/drive/MyDrive/Colab Notebooks'

# 2. Function to load and clean a model file on the fly
def load_fixed_module(file_name, module_name):
    file_path = os.path.join(model_folder_path, file_name)
    if not os.path.exists(file_path):
        print(f"Error: {file_name} not found at {file_path}")
        return None

    with open(file_path, 'r', encoding='utf-8') as f:
        raw_content = f.read()

    code_text = ""
    # Try to parse as Jupyter notebook JSON
    try:
        notebook_data = json.loads(raw_content)
        python_code_parts = []
        for cell in notebook_data.get('cells', []):
            if cell.get('cell_type') == 'code':
                # Join source lines, ensuring they are strings, and add a newline
                python_code_parts.append(''.join(cell.get('source', [])))
        code_text = '\n'.join(python_code_parts)
        if not code_text.strip(): # If no code found in JSON, might be empty notebook or malformed
            raise ValueError("No executable code found in Jupyter notebook format.")
        print(f"Detected {file_name} as Jupyter notebook, extracted code.")
    except json.JSONDecodeError:
        # Not a JSON, assume it's a plain Python file
        code_text = raw_content
        print(f"Detected {file_name} as plain Python file.")
    except ValueError as e:
        print(f"Warning: Failed to extract code from {file_name} as Jupyter notebook: {e}. Treating as plain Python.")
        code_text = raw_content

    # Aggressively replace any lowercase javascript booleans with Python ones
    code_text = re.sub(r'\btrue\b', 'True', code_text, flags=re.IGNORECASE)
    code_text = re.sub(r'\bfalse\b', 'False', code_text, flags=re.IGNORECASE)

    # Create module container
    spec = importlib.util.spec_from_file_location(module_name, file_path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = mod

    # Execute the cleaned code
    try:
        exec(code_text, mod.__dict__) # This executes the *string* content
        print(f"Successfully loaded and cleaned {module_name}!")
        return mod
    except Exception as e:
        print(f"Error executing code for {module_name}: {e}")
        return None

# 3. Load both models safely
model_1 = load_fixed_module('MODEL_1.py', 'model_1')
model_2 = load_fixed_module('MODEL_2.py', 'model_2')

import matplotlib.pyplot as plt
import os

GRAPH_FOLDER = "/content/model_2_graphs"
os.makedirs(GRAPH_FOLDER, exist_ok=True)

# Remove old graph files
for file in os.listdir(GRAPH_FOLDER):
    file_path = os.path.join(GRAPH_FOLDER, file)
    if os.path.isfile(file_path):
        os.remove(file_path)

saved_figures = []
original_show = plt.show


# Save each figure whenever Model 2 calls plt.show()
def save_model_2_graph(*args, **kwargs):

    for num in plt.get_fignums():

        fig = plt.figure(num)

        if fig not in saved_figures:

            graph_number = len(saved_figures) + 1

            if graph_number <= 5:

                graph_path = os.path.join(
                    GRAPH_FOLDER,
                    f"graph_{graph_number}.png"
                )

                fig.savefig(
                    graph_path,
                    dpi=150,
                    bbox_inches="tight"
                )

                saved_figures.append(fig)

                print(f"Graph {graph_number} saved.")


# IMPORTANT:
# Intercept plt.show BEFORE MODEL_2.py is executed
plt.show = save_model_2_graph


try:

    print("Reloading Model 2 with graph capture enabled...")

    graph_model_2 = load_fixed_module(
        "MODEL_2.py",
        "model_2_graph_capture"
    )

    # Catch any figures that may still be open
    for num in plt.get_fignums():

        fig = plt.figure(num)

        if fig not in saved_figures:

            graph_number = len(saved_figures) + 1

            if graph_number <= 5:

                graph_path = os.path.join(
                    GRAPH_FOLDER,
                    f"graph_{graph_number}.png"
                )

                fig.savefig(
                    graph_path,
                    dpi=150,
                    bbox_inches="tight"
                )

                saved_figures.append(fig)

                print(f"Graph {graph_number} saved.")


finally:

    # Restore normal matplotlib behavior
    plt.show = original_show


print()
print(f"Saved {len(saved_figures)} graphs.")

for i in range(1, 6):

    graph_path = os.path.join(
        GRAPH_FOLDER,
        f"graph_{i}.png"
    )

    if os.path.exists(graph_path):
        print(f"Graph {i}: saved")
    else:
        print(f"Graph {i}: not found")

import gradio as gr
import matplotlib.pyplot as plt
import numpy as np
import time
from PIL import Image
import os

GRAPH_FOLDER = "/content/model_2_graphs"

def predict_cytarabine(file):
    if file is None:
        raise gr.Error('Please upload a cell line data file first!')

    time.sleep(1)

    # 1. Run model_1 safely
    model_1_output = None
    if 'model_1' in globals() and hasattr(model_1, 'run'):
        try:
            model_1_output = model_1.run(file)
        except Exception as e:
            print(f"model_1 execution note: {e}")

    # 2. Run model_2 normally
    model_2_output = None
    try:
        if 'model_2' in globals() and hasattr(model_2, 'run'):
            model_2_output = model_2.run(model_1_output, file)
    except Exception as e:
        print(f"model_2 execution error: {e}")

    # 3. Load the saved graphs
    saved_graphs = []

    for i in range(1, 6):
        graph_path = os.path.join(
            GRAPH_FOLDER,
            f"graph_{i}.png"
        )

        if os.path.exists(graph_path):
            saved_graphs.append(graph_path)
        else:
            saved_graphs.append(None)

    # 4. Extract text strings or dataframe descriptions from model_2 output
    extracted_texts = []

    if isinstance(model_2_output, (list, tuple)):
        for item in model_2_output:
            if isinstance(item, str):
                extracted_texts.append(item)
            elif hasattr(item, 'to_string'):
                extracted_texts.append(str(item))

    # 5. Build the exact 10-item tuple required by Gradio
    response_items = []

    for i in range(5):

        if saved_graphs[i] is not None:
            response_items.append(saved_graphs[i])
        else:
            response_items.append(None)

        if i < len(extracted_texts):
            response_items.append(extracted_texts[i])
        else:
            response_items.append(f"Analysis insights for Graph {i+1}.")

    return tuple(response_items)

# Custom CSS for the neobrutalist layout
custom_css = """
body {
    background-color: #FFFFFF !important;
    font-family: 'Courier New', Courier, monospace !important;
}
.gradio-container {
    background-color: #FFFFFF !important;
    border: 3px solid #000000;
    border-radius: 20px;
    box-shadow: 6px 6px 0px #000000;
    padding: 30px;
    margin-top: 20px;
    margin-bottom: 20px;
}
button.primary {
    background-color: #1A365D !important;
    color: #FFFFFF !important;
    border: 3px solid #000000 !important;
    border-radius: 12px !important;
    font-weight: bold !important;
    box-shadow: 3px 3px 0px #000000 !important;
}
button.primary:hover {
    background-color: #2B6CB0 !important;
}
"""

with gr.Blocks() as demo:
    gr.Markdown('# 🍪 Let\'s Predict Cytarabine Resistance Together! 🧬')
    gr.Markdown('Upload your cell line data below and let the models run their true pipeline.')

    file_input = gr.File(label='📂 Upload Cell Line Data')
    btn = gr.Button('🚀 Run Prediction & Reasoning', variant="primary")

    gr.Markdown('---')
    gr.Markdown('### ✨ Model Results & Insights')

    plot1 = gr.Image(label='Graph 1')
    out1 = gr.Textbox(label='Less LN_IC50 represents more sensitivity to drug Cytarabine.')

    plot2 = gr.Image(label='Graph 2')
    out2 = gr.Textbox(label='Red line- line of perfect prediction & Blue dots-predicted vs actual LN_IC50 values.')

    plot3 = gr.Image(label='Graph 3')
    out3 = gr.Textbox(label='Feature importance shows how much each feature contributed to the prediction of the model.')

    plot4 = gr.Image(label='Graph 4')
    out4 = gr.Textbox(label='This heatmap visualizes the true and predicted classifications of the model for Cytarabine resistance (1) and sensitivity (0) on the test set.')

    plot5 = gr.Image(label='Graph 5')
    out5 = gr.Textbox(label='The top 10 features with non-zero coefficients identified by the LASSO classifier, indicating their linear predictive strength.')

    btn.click(
        fn=predict_cytarabine,
        inputs=file_input,
        outputs=[plot1, out1, plot2, out2, plot3, out3, plot4, out4, plot5, out5],
    )

demo.launch(share=True, css=custom_css)